# Generated by Django 5.1.3 on 2025-01-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Categories',
        ),
    ]
