# Generated by Django 5.1.3 on 2025-01-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_portal', '0002_rename_categorys_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
