# Generated by Django 5.1.3 on 2025-01-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_portal', '0004_alter_create_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='full_description',
            field=models.CharField(blank=True, max_length=3500, null=True),
        ),
    ]
