# Generated by Django 5.1.3 on 2025-01-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_portal', '0005_alter_courses_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='full_description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
