# Generated by Django 5.1.3 on 2025-01-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_portal', '0007_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='create_account',
            name='dob',
            field=models.DateField(),
        ),
    ]
