# Generated by Django 5.1.3 on 2025-01-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_portal', '0010_my_learning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_learning',
            old_name='course_name',
            new_name='course',
        ),
    ]
