# Generated by Django 5.1.3 on 2025-01-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_portal', '0011_rename_course_name_my_learning_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_learning',
            name='course',
            field=models.IntegerField(),
        ),
    ]
