# Generated by Django 5.1.3 on 2025-01-30 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_portal', '0012_alter_my_learning_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_learning',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_portal.courses'),
        ),
    ]
